// NOTIFICATIONS
export const NOTIFICATION_SHOW = 'NOTIFICATION_SHOW'
export const NOTIFICATION_DISMISS = 'NOTIFICATION_DISMISS'
export const NOTIFICATION_CLEAR = 'NOTIFICATION_CLEAR'

// QUIZ
export const ADD_QUIZ = 'ADD_QUIZ'
export const REQUEST_LIST_QUIZ = 'REQUEST_LIST_QUIZ'
export const SUCCESS_LIST_QUIZ = 'SUCCESS_LIST_QUIZ'
export const FAILURE_LIST_QUIZ = 'FAILURE_LIST_QUIZ'
