/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'dev';

// Config for firebase
export const firebase = {
  apiKey: 'AIzaSyBeDVXES100j7po8MBfXFCPOIHBik9bYHk',
  authDomain: 'hiredbyreact.firebaseapp.com',
  databaseURL: 'https://hiredbyreact.firebaseio.com',
  projectId: 'hiredbyreact',
  storageBucket: 'hiredbyreact.appspot.com',
  messagingSenderId: '723299675655'
};

// Config to override default reduxFirebase config in store/createStore
// which is not environment specific.
// For more details, visit http://react-redux-firebase.com/docs/api/enhancer.html
export const reduxFirebase = {
  enableLogging: false // enable/disable Firebase Database Logging
};

export const analyticsTrackingId = '';

export const publicVapidKey = '';

export const sentryDsn = 'https://68ffd8ab470d44e482798f4cfc823cc4@sentry.io/1421624';

export default {
  env,
  firebase,
  reduxFirebase,
  sentryDsn,
  analyticsTrackingId
};
